// @formality/core - Framework-agnostic form utilities
// This package has ZERO framework dependencies

// ============================================================================
// Types
// ============================================================================
export type {
  // Config types
  SelectValue,
  SelectFunction,
  InputConfig,
  FieldConfig,
  FormFieldsConfig,
  GroupConfig,
  FormConfig,
  FormalityProviderConfig,
  InputTemplateProps,
  // State types
  FieldError,
  FieldState,
  FormState,
  // Condition types
  ConditionDescriptor,
  ConditionResult,
  // Validation types
  ValidationResult,
  ValidatorFunction,
  ValidatorSpec,
  ValidatorFactory,
  ValidatorsConfig,
  ErrorMessagesConfig,
} from './types';

// ============================================================================
// Expression Engine
// ============================================================================
export type { EvaluationContext } from './expression';

export {
  evaluate,
  evaluateDescriptor,
  clearExpressionCache,
  QUALIFIED_PREFIXES,
  KEYWORDS,
  FIELD_PROXY_MARKER,
  FIELD_PROXY_VALUE,
  buildFormContext,
  buildFieldContext,
  buildEvaluationContext,
  createFieldStateProxy,
  isFieldProxy,
  unwrapFieldProxy,
  inferFieldsFromExpression,
  inferFieldsFromDescriptor,
} from './expression';

// ============================================================================
// Conditions
// ============================================================================
export type { EvaluateConditionsInput, FieldStateInput } from './conditions';

export {
  evaluateConditions,
  conditionMatches,
  mergeConditionResults,
  inferFieldsFromConditions,
} from './conditions';

// ============================================================================
// Validation
// ============================================================================
export {
  runValidator,
  runValidatorSync,
  isValid,
  composeValidators,
  required,
  minLength,
  maxLength,
  pattern,
  resolveErrorMessage,
  formatTypeAsMessage,
  createErrorMessages,
  getErrorType,
  createValidationError,
} from './validation';

// ============================================================================
// Transform Pipeline
// ============================================================================
export type {
  ParserFunction,
  FormatterFunction,
  ParserSpec,
  FormatterSpec,
  ParsersConfig,
  FormattersConfig,
} from './transform';

export {
  parse,
  format,
  extractValueField,
  transformFieldName,
  createFloatParser,
  createFloatFormatter,
  createIntParser,
  createTrimParser,
  createDefaultParsers,
  createDefaultFormatters,
} from './transform';

// ============================================================================
// Configuration
// ============================================================================
export {
  deepMerge,
  mergeInputConfigs,
  resolveInputConfig,
  resolveFieldType,
  mergeStaticProps,
  mergeFieldProps,
  createConfigContext,
  resolveInitialValue,
  resolveAllInitialValues,
  isEmptyValue,
  getInputDefaultValue,
  mergeRecordWithDefaults,
} from './config';

// ============================================================================
// Labels & Ordering
// ============================================================================
export {
  humanizeLabel,
  resolveLabel,
  resolveFormTitle,
  isAutoGeneratedLabel,
  createLabelWithUnit,
  parseLabelWithUnit,
  sortFieldsByOrder,
  getUnusedFields,
  getOrderedUnusedFields,
} from './labels';
